/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld_Employee */

#ifndef _Included_HelloWorld_Employee
#define _Included_HelloWorld_Employee
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
